# This is a basic workflow to help you get started with Actions

name: Deploy to Tencent serverless

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.1.1
      with:
        node-version: '12'
    - uses: ruby/setup-ruby@v1.40.0
      with:
        ruby-version: 2.6
        bundler-cache: true

    - name: Generate jekyll
      run: |
        cd ./docs
        bundle install --path vendor/bundle
        bundle exec jekyll build
    
    - name: Deploy serverless
      run: |
        npm install -g serverless
        serverless deploy --debug
      env: 
        SERVERLESS_PLATFORM_VENDOR: tencent
        TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
        TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
    
    
